# General Jekyll Config
pygments: true
url: http://fantaghiro.github.io
lsi: false
exclude: [LICENSE, CNAME, README.md, .gitignore]
permalink: /:month-:day-:year/:title.html
markdown: redcarpet
redcarpet:
  extensions: 
  # 使用```快速开始代码块
  - fenced_code_blocks
  # 自动解析链接，这样就不用写讨厌的[http://link](http://link)格式了
  - autolink
  # 表格扩展
  - tables

# Theme customization - please change from the defaults!
theme:
  # Color for top bar, links, etc
  highlight_color: '#cb4b16'

  # Profile links on the left sidebar, leave blank to ignore
  social:
    github: fantaghiro

  # "Hi, I'm _______"
  name: Amanda Wang
  email: happy.wangpei@gmail.com
  tagline: "weak opinions, strongly held"

  # Google Analytics key, leave blank to ignore
  google_analytics_key: UA-xxxx-x

  # Toggle "Postings are my own" disclaimer in footer
  show_disclaimer: true
